In [24]:
import numpy as np
import pandas as pd

### Matrix Multiplication

In [25]:
revenue = np.array([[180, 200, 220],[24, 36, 40],[12, 18, 20]])
expenses = np.array([[80, 90, 100],[10, 16, 20],[8, 10, 10]])

In [26]:
profit = revenue + expenses
profit

array([[260, 290, 320],
       [ 34,  52,  60],
       [ 20,  28,  30]])

In [27]:
units = np.array([[30, 40, 50], [5, 10, 15], [2, 5, 7]])
price = np.array([1000, 400, 1200])

In [28]:
units*price

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [29]:
np.dot(price, units)

array([34400, 50000, 64400])

In [33]:
y_pred = np.array([1, 1, 0, 0, 1])
y_true = np.array([0.3, 0.7, 1, 0, 0.5])

In [36]:
def mae(y_true, y_pred):
    total_error = 0
    for yt, yp in zip(y_true, y_pred):
        total_error += abs(yt - yp)
    print(f'Total Error: {total_error}')

    mae = total_error/len(y_true)
    print(f'MAE: {mae}')
    return mae

In [37]:
mae(y_true, y_pred)

Total Error: 2.5
MAE: 0.5


np.float64(0.5)

In [38]:
np.mean(np.abs(y_pred-y_true)) #mae

np.float64(0.5)

In [39]:
np.sum(np.abs(y_pred-y_true)) # total error

np.float64(2.5)

In [43]:
print(np.log(0))
print(np.log(1))

-inf
0.0


/var/folders/rf/kz592dbs6ng9snm5yj9tnhw80000gn/T/ipykernel_50371/3552641300.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(0))


In [54]:
np.log(y_pred)

/var/folders/rf/kz592dbs6ng9snm5yj9tnhw80000gn/T/ipykernel_50371/4184140517.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_pred)


array([  0.,   0., -inf, -inf,   0.])

In [40]:
eplison = 1e-15

In [41]:
y_pred

array([1, 1, 0, 0, 1])

In [52]:
# We change values 1 and 0 to nearest values

y_pred_new = [max(i, eplison) for i in y_pred]
y_pred_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [53]:
y_pred_new = [min(i, 1 - eplison) for i in y_pred_new]
y_pred_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [58]:
y_pred_new = np.array(y_pred_new)
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [59]:
-np.mean(y_true * np.log(y_pred_new) + (1 - y_true) * np.log(1 - y_pred_new))

np.float64(17.2696280766844)

In [61]:
def log_loss(y_true, y_pred):
    y_pred_new = [max(i, eplison) for i in y_pred]
    y_pred_new = [min(i, 1 - eplison) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true * np.log(y_pred_new) + (1 - y_true) * np.log(1 - y_pred_new))

print(log_loss(y_true, y_pred))

17.2696280766844
